#!/usr/bin/env bash
# =============================================================================
#  CAD to USD Converter - Installer (Linux)
#
#  Zero-dependency setup. Just run this once:
#    ./install.sh
#
#  What it does:
#    1. Checks for uv + Python 3.12
#    2. Creates a .venv virtual environment (isolated, won't touch your system)
#    3. Installs omniverse-kit from pypi.nvidia.com (~500 MB, one-time)
#    4. Accepts the NVIDIA EULA non-interactively
#    5. Writes config.env (used by all .sh scripts automatically)
#    6. Pre-downloads omni.kit.converter.cad from the NVIDIA extension registry
#    7. Validates the installation
#
#  Requirements:
#    - Linux x86_64 (Ubuntu 22.04+ / glibc >= 2.35)
#    - uv  (https://docs.astral.sh/uv/getting-started/installation/)
#    - Internet access to pypi.nvidia.com
#    - System packages (Ubuntu/Debian):
#        sudo apt-get install -y ca-certificates libxml2 libgl1 libxt6 \
#          libglib2.0-0 libsm6 libxext6 libxrender1 libxi6 libgomp1
# =============================================================================

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="$REPO/.venv"

echo ""
echo " ============================================================"
echo "  CAD to USD Converter - Setup"
echo "  Powered by NVIDIA omniverse-kit + omni.kit.asset_converter"
echo " ============================================================"
echo ""

# ==========================================================================
#  STEP 1 — Check uv
# ==========================================================================
echo " [1/6] Checking uv..."
if ! command -v uv &>/dev/null; then
    echo " [ERROR] uv not found."
    echo "         Install it with:"
    echo "           curl -LsSf https://astral.sh/uv/install.sh | sh"
    echo "         Then re-run this script."
    exit 1
fi
UV_VERSION="$(uv --version 2>&1 | head -1)"
echo " [OK]  $UV_VERSION"
echo ""

# ==========================================================================
#  STEP 2 — Create virtual environment with Python 3.12
# ==========================================================================
echo " [2/6] Setting up virtual environment (.venv with Python 3.12)..."
if [[ -f "$VENV/bin/python" ]]; then
    EXISTING_VER="$("$VENV/bin/python" --version 2>&1)"
    echo " [OK]  .venv already exists ($EXISTING_VER) — reusing it"
else
    echo "       Creating .venv..."
    uv venv --python 3.12 "$VENV"
    echo " [OK]  .venv created at $VENV"
fi
VENV_PY="$VENV/bin/python"
echo ""

# ==========================================================================
#  STEP 3 — Upgrade pip inside venv
# ==========================================================================
echo " [3/6] Upgrading pip..."
uv pip install --python "$VENV_PY" --upgrade pip --quiet
echo " [OK]  pip up to date"
echo ""

# ==========================================================================
#  STEP 4 — Install omniverse-kit
# ==========================================================================
echo " [4/6] Installing omniverse-kit..."
echo "        Source : https://pypi.nvidia.com (public — no login required)"
echo "        Size   : ~500 MB (downloaded once, cached in the venv)"
echo ""

if "$VENV_PY" -c "import omni" &>/dev/null 2>&1; then
    echo " [OK]  omniverse-kit already installed — skipping download"
else
    uv pip install --python "$VENV_PY" \
        omniverse-kit \
        --extra-index-url https://pypi.nvidia.com
    echo " [OK]  omniverse-kit installed"
fi
echo ""

# ==========================================================================
#  STEP 5 — Write config.env
# ==========================================================================
echo " [5/6] Writing config.env..."
cat > "$REPO/config.env" <<EOF
# CAD to USD Converter — Configuration
# Auto-generated by install.sh — re-run to regenerate

PYTHON_EXE=$VENV_PY
OMNI_KIT_ACCEPT_EULA=yes
DEFAULT_OUTPUT_FORMAT=.usd
TESSELLATION_CHORD=0.01
TESSELLATION_ANGLE=30
EOF
echo " [OK]  config.env written"
echo ""

# ==========================================================================
#  STEP 6 — Pre-download CAD converter extension
# ==========================================================================
echo " [6/6] Downloading CAD converter extension (omni.kit.converter.cad)..."
echo "        This fetches HOOPS Exchange + CAD format translators on first run."
echo "        May take 2-3 minutes depending on network speed."
echo ""

export OMNI_KIT_ACCEPT_EULA=yes
"$VENV_PY" "$REPO/setup/fetch_cad_ext.py" || {
    echo ""
    echo " [WARN] CAD extension download incomplete — will retry on first convert."
    echo "        Open formats: STEP, IGES, OBJ, FBX, glTF work without it."
    echo ""
}

# ==========================================================================
#  Validate
# ==========================================================================
"$VENV_PY" "$REPO/setup/validate_env.py"

echo " ============================================================"
echo "  Setup complete!"
echo " ============================================================"
echo ""
echo "  Convert a file:    ./convert.sh  input.prt  [output.usd]"
echo "  Batch a folder:    ./batch_convert.sh  /path/to/cad  /path/to/usd"
echo "  Check your setup:  ./validate.sh"
echo "  Supported formats: ./convert.sh --formats"
echo ""
echo "  The .venv folder holds the isolated Python environment."
echo "  You never need to activate it — the .sh scripts handle it."
echo ""
